name: jusstalk
options:
  bundleIdPrefix: com.jusstalk
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

targets:
  jusstalk:
    type: application
    platform: iOS
    sources:
      - path: Sources
        type: group
      - path: Resources
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jusstalk.app
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
      config:
        Debug:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          SWIFT_OPTIMIZATION_LEVEL: -O
          STRIP_DEBUG_SYMBOLS: YES
          STRIP_SWIFT_SYMBOLS: YES
          ENABLE_BITCODE: NO

    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: Jusstalk
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        CFBundleIdentifier: com.jusstalk.app
        NSMicrophoneUsageDescription: jusstalk needs microphone access to record audio for transcription.
        UILaunchScreen:
          UIColorName: ""
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

schemes:
  jusstalk:
    build:
      targets:
        jusstalk: all
    run:
      config: Debug
    archive:
      config: Release
